class Surah {
  final int id;
  final String name;
  final String englishName;
  final int versesCount;

  const Surah({
    required this.id,
    required this.name,
    required this.englishName,
    required this.versesCount,
  });
}

class QuranData {
  static const List<Surah> surahs = [
    Surah(id: 1, name: "الفاتحة", englishName: "Al-Fatiha", versesCount: 7),
    Surah(id: 2, name: "البقرة", englishName: "Al-Baqarah", versesCount: 286),
    Surah(id: 3, name: "آل عمران", englishName: "Ali 'Imran", versesCount: 200),
    Surah(id: 4, name: "النساء", englishName: "An-Nisa", versesCount: 176),
    Surah(id: 5, name: "المائدة", englishName: "Al-Ma'idah", versesCount: 120),
    Surah(id: 6, name: "الأنعام", englishName: "Al-An'am", versesCount: 165),
    Surah(id: 7, name: "الأعراف", englishName: "Al-A'raf", versesCount: 206),
    Surah(id: 8, name: "الأنفال", englishName: "Al-Anfal", versesCount: 75),
    Surah(id: 9, name: "التوبة", englishName: "At-Tawbah", versesCount: 129),
    Surah(id: 10, name: "يونس", englishName: "Yunus", versesCount: 109),
    Surah(id: 11, name: "هود", englishName: "Hud", versesCount: 123),
    Surah(id: 12, name: "يوسف", englishName: "Yusuf", versesCount: 111),
    Surah(id: 13, name: "الرعد", englishName: "Ar-Ra'd", versesCount: 43),
    Surah(id: 14, name: "إبراهيم", englishName: "Ibrahim", versesCount: 52),
    Surah(id: 15, name: "الحجر", englishName: "Al-Hijr", versesCount: 99),
    Surah(id: 16, name: "النحل", englishName: "An-Nahl", versesCount: 128),
    Surah(id: 17, name: "الإسراء", englishName: "Al-Isra", versesCount: 111),
    Surah(id: 18, name: "الكهف", englishName: "Al-Kahf", versesCount: 110),
    Surah(id: 19, name: "مريم", englishName: "Maryam", versesCount: 98),
    Surah(id: 20, name: "طه", englishName: "Taha", versesCount: 135),
    Surah(id: 21, name: "الأنبياء", englishName: "Al-Anbiya", versesCount: 112),
    Surah(id: 22, name: "الحج", englishName: "Al-Hajj", versesCount: 78),
    Surah(id: 23, name: "المؤمنون", englishName: "Al-Mu'minun", versesCount: 118),
    Surah(id: 24, name: "النور", englishName: "An-Nur", versesCount: 64),
    Surah(id: 25, name: "الفرقان", englishName: "Al-Furqan", versesCount: 77),
    Surah(id: 26, name: "الشعراء", englishName: "Ash-Shu'ara", versesCount: 227),
    Surah(id: 27, name: "النمل", englishName: "An-Naml", versesCount: 93),
    Surah(id: 28, name: "القصص", englishName: "Al-Qasas", versesCount: 88),
    Surah(id: 29, name: "العنكبوت", englishName: "Al-'Ankabut", versesCount: 69),
    Surah(id: 30, name: "الروم", englishName: "Ar-Rum", versesCount: 60),
    Surah(id: 31, name: "لقمان", englishName: "Luqman", versesCount: 34),
    Surah(id: 32, name: "السجدة", englishName: "As-Sajdah", versesCount: 30),
    Surah(id: 33, name: "الأحزاب", englishName: "Al-Ahzab", versesCount: 73),
    Surah(id: 34, name: "سبأ", englishName: "Saba", versesCount: 54),
    Surah(id: 35, name: "فاطر", englishName: "Fatir", versesCount: 45),
    Surah(id: 36, name: "يس", englishName: "Ya-Sin", versesCount: 83),
    Surah(id: 37, name: "الصافات", englishName: "As-Saffat", versesCount: 182),
    Surah(id: 38, name: "ص", englishName: "Sad", versesCount: 88),
    Surah(id: 39, name: "الزمر", englishName: "Az-Zumar", versesCount: 75),
    Surah(id: 40, name: "غافر", englishName: "Ghafir", versesCount: 85),
    Surah(id: 41, name: "فصلت", englishName: "Fussilat", versesCount: 54),
    Surah(id: 42, name: "الشورى", englishName: "Ash-Shuraa", versesCount: 53),
    Surah(id: 43, name: "الزخرف", englishName: "Az-Zukhruf", versesCount: 89),
    Surah(id: 44, name: "الدخان", englishName: "Ad-Dukhan", versesCount: 59),
    Surah(id: 45, name: "الجاثية", englishName: "Al-Jathiyah", versesCount: 37),
    Surah(id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", versesCount: 35),
    Surah(id: 47, name: "محمد", englishName: "Muhammad", versesCount: 38),
    Surah(id: 48, name: "الفتح", englishName: "Al-Fath", versesCount: 29),
    Surah(id: 49, name: "الحجرات", englishName: "Al-Hujurat", versesCount: 18),
    Surah(id: 50, name: "ق", englishName: "Qaf", versesCount: 45),
    Surah(id: 51, name: "الذاريات", englishName: "Adh-Dhariyat", versesCount: 60),
    Surah(id: 52, name: "الطور", englishName: "At-Tur", versesCount: 49),
    Surah(id: 53, name: "النجم", englishName: "An-Najm", versesCount: 62),
    Surah(id: 54, name: "القمر", englishName: "Al-Qamar", versesCount: 55),
    Surah(id: 55, name: "الرحمن", englishName: "Ar-Rahman", versesCount: 78),
    Surah(id: 56, name: "الواقعة", englishName: "Al-Waqi'ah", versesCount: 96),
    Surah(id: 57, name: "الحديد", englishName: "Al-Hadid", versesCount: 29),
    Surah(id: 58, name: "المجادلة", englishName: "Al-Mujadila", versesCount: 22),
    Surah(id: 59, name: "الحشر", englishName: "Al-Hashr", versesCount: 24),
    Surah(id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", versesCount: 13),
    Surah(id: 61, name: "الصف", englishName: "As-Saff", versesCount: 14),
    Surah(id: 62, name: "الجمعة", englishName: "Al-Jumu'ah", versesCount: 11),
    Surah(id: 63, name: "المنافقون", englishName: "Al-Munafiqun", versesCount: 11),
    Surah(id: 64, name: "التغابن", englishName: "At-Taghabun", versesCount: 18),
    Surah(id: 65, name: "الطلاق", englishName: "At-Talaq", versesCount: 12),
    Surah(id: 66, name: "التحريم", englishName: "At-Tahrim", versesCount: 12),
    Surah(id: 67, name: "الملك", englishName: "Al-Mulk", versesCount: 30),
    Surah(id: 68, name: "القلم", englishName: "Al-Qalam", versesCount: 52),
    Surah(id: 69, name: "الحاقة", englishName: "Al-Haqqah", versesCount: 52),
    Surah(id: 70, name: "المعارج", englishName: "Al-Ma'arij", versesCount: 44),
    Surah(id: 71, name: "نوح", englishName: "Nuh", versesCount: 28),
    Surah(id: 72, name: "الجن", englishName: "Al-Jinn", versesCount: 28),
    Surah(id: 73, name: "المزمل", englishName: "Al-Muzzammil", versesCount: 20),
    Surah(id: 74, name: "المدثر", englishName: "Al-Muddaththir", versesCount: 56),
    Surah(id: 75, name: "القيامة", englishName: "Al-Qiyamah", versesCount: 40),
    Surah(id: 76, name: "الإنسان", englishName: "Al-Insan", versesCount: 31),
    Surah(id: 77, name: "المرسلات", englishName: "Al-Mursalat", versesCount: 50),
    Surah(id: 78, name: "النبأ", englishName: "An-Naba", versesCount: 40),
    Surah(id: 79, name: "النازعات", englishName: "An-Nazi'at", versesCount: 46),
    Surah(id: 80, name: "عبس", englishName: "'Abasa", versesCount: 42),
    Surah(id: 81, name: "التكوير", englishName: "At-Takwir", versesCount: 29),
    Surah(id: 82, name: "الانفطار", englishName: "Al-Infitar", versesCount: 19),
    Surah(id: 83, name: "المطففين", englishName: "Al-Mutaffifin", versesCount: 36),
    Surah(id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", versesCount: 25),
    Surah(id: 85, name: "البروج", englishName: "Al-Buruj", versesCount: 22),
    Surah(id: 86, name: "الطارق", englishName: "At-Tariq", versesCount: 17),
    Surah(id: 87, name: "الأعلى", englishName: "Al-A'la", versesCount: 19),
    Surah(id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", versesCount: 26),
    Surah(id: 89, name: "الفجر", englishName: "Al-Fajr", versesCount: 30),
    Surah(id: 90, name: "البلد", englishName: "Al-Balad", versesCount: 20),
    Surah(id: 91, name: "الشمس", englishName: "Ash-Shams", versesCount: 15),
    Surah(id: 92, name: "الليل", englishName: "Al-Layl", versesCount: 21),
    Surah(id: 93, name: "الضحى", englishName: "Ad-Duhaa", versesCount: 11),
    Surah(id: 94, name: "الشرح", englishName: "Ash-Sharh", versesCount: 8),
    Surah(id: 95, name: "التين", englishName: "At-Tin", versesCount: 8),
    Surah(id: 96, name: "العلق", englishName: "Al-'Alaq", versesCount: 19),
    Surah(id: 97, name: "القدر", englishName: "Al-Qadr", versesCount: 5),
    Surah(id: 98, name: "البينة", englishName: "Al-Bayyinah", versesCount: 8),
    Surah(id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", versesCount: 8),
    Surah(id: 100, name: "العاديات", englishName: "Al-'Adiyat", versesCount: 11),
    Surah(id: 101, name: "القارعة", englishName: "Al-Qari'ah", versesCount: 11),
    Surah(id: 102, name: "التكاثر", englishName: "At-Takathur", versesCount: 8),
    Surah(id: 103, name: "العصر", englishName: "Al-'Asr", versesCount: 3),
    Surah(id: 104, name: "الهمزة", englishName: "Al-Humazah", versesCount: 9),
    Surah(id: 105, name: "الفيل", englishName: "Al-Fil", versesCount: 5),
    Surah(id: 106, name: "قريش", englishName: "Quraysh", versesCount: 4),
    Surah(id: 107, name: "الماعون", englishName: "Al-Ma'un", versesCount: 7),
    Surah(id: 108, name: "الكوثر", englishName: "Al-Kawthar", versesCount: 3),
    Surah(id: 109, name: "الكافرون", englishName: "Al-Kafirun", versesCount: 6),
    Surah(id: 110, name: "النصر", englishName: "An-Nasr", versesCount: 3),
    Surah(id: 111, name: "المسد", englishName: "Al-Masad", versesCount: 5),
    Surah(id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", versesCount: 4),
    Surah(id: 113, name: "الفلق", englishName: "Al-Falaq", versesCount: 5),
    Surah(id: 114, name: "الناس", englishName: "An-Nas", versesCount: 6),
  ];
}